-- LitienGuard — Cerebro corpus moved from static TypeScript to Supabase
-- Allows admin curation without redeploying the app.

create table if not exists public.cerebro_chunks (
  id text primary key,
  source text not null,
  page text not null,
  title text not null,
  content text not null,
  meta jsonb default '{}'::jsonb,
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  created_by uuid references public.profiles(id),
  updated_by uuid references public.profiles(id)
);

create index if not exists cerebro_chunks_active_idx
  on public.cerebro_chunks(is_active) where is_active = true;
create index if not exists cerebro_chunks_source_idx
  on public.cerebro_chunks(source);

drop trigger if exists cerebro_chunks_updated_at on public.cerebro_chunks;
create trigger cerebro_chunks_updated_at
  before update on public.cerebro_chunks
  for each row execute function public.touch_updated_at();

-- RLS
alter table public.cerebro_chunks enable row level security;

-- Authenticated users can read active chunks (needed by the BM25 server-side
-- index loader). Inactive chunks are not visible to non-admins.
drop policy if exists "auth read active chunks" on public.cerebro_chunks;
create policy "auth read active chunks"
  on public.cerebro_chunks for select
  using (
    is_active = true
    or public.is_admin()
  );

drop policy if exists "admin manage chunks" on public.cerebro_chunks;
create policy "admin manage chunks"
  on public.cerebro_chunks
  for all
  using (public.is_admin())
  with check (public.is_admin());

-- Seed: initial 50 chunks (paraphrased from public guidelines)
insert into public.cerebro_chunks (id, source, page, title, content, meta) values
('ada-2024-hba1c-metas','ADA Standards of Care 2024','S6.2','Metas glucémicas en adultos no embarazadas con DM','Se sugiere meta de HbA1c menor de 7.0% para la mayoría de adultos con DM no embarazadas. Considerar metas más estrictas (menor de 6.5%) en pacientes seleccionados con DM de corta evolución, expectativa de vida larga y sin enfermedad cardiovascular significativa, siempre que sea alcanzable sin hipoglucemia o efectos adversos. Metas menos estrictas (menor de 8.0%) en pacientes con historia de hipoglucemia severa, expectativa de vida limitada, complicaciones micro o macrovasculares avanzadas o comorbilidades extensas.','{"especialidad":"endocrinología","año":"2024"}'),
('ada-2024-metformina','ADA Standards of Care 2024','S9','Metformina como primera línea farmacológica en DM2','Metformina sigue siendo el agente preferido para el tratamiento inicial de la DM2 cuando no existe contraindicación. Iniciar 500 mg vía oral una vez al día con la cena, titular semanal hasta dosis usual 1500-2000 mg/día divididos. Suspender temporalmente ante estados de deshidratación, contraste yodado y procedimientos quirúrgicos. Contraindicada con TFGe menor de 30 mL/min/1.73m².','{"especialidad":"endocrinología","año":"2024"}'),
('ada-2024-sglt2-asccd','ADA Standards of Care 2024','S9.22','iSGLT2 con beneficio cardiovascular y renal en DM2','En pacientes con DM2 y enfermedad cardiovascular aterosclerótica establecida, insuficiencia cardiaca o enfermedad renal crónica, se recomienda agregar un inhibidor de SGLT2 con beneficio demostrado (empagliflozina, dapagliflozina o canagliflozina) independientemente de la HbA1c basal o del uso de metformina. La empagliflozina y dapagliflozina están aprobadas hasta TFGe 20-25 mL/min/1.73m² según indicación renal o de IC.','{"especialidad":"endocrinología / cardiología","año":"2024"}'),
('ada-2024-glp1','ADA Standards of Care 2024','S9.20','Agonistas GLP-1 en DM2 con ASCVD o obesidad','Considerar un agonista del receptor de GLP-1 con beneficio cardiovascular comprobado (semaglutida, dulaglutida, liraglutida) en pacientes con DM2 y ASCVD o múltiples factores de riesgo cardiovascular, así como cuando se requiere pérdida de peso. Tirzepatida (agonista dual GIP/GLP-1) tiene la mayor eficacia para pérdida de peso y reducción de HbA1c entre los agentes incretínicos.','{"especialidad":"endocrinología","año":"2024"}'),
('imss-718-hipoglucemia','GPC IMSS SS-718-15','33','Manejo de hipoglucemia en DM','Ante hipoglucemia leve a moderada (glucemia menor de 70 mg/dL con conciencia preservada) administrar 15 g de carbohidratos de absorción rápida vía oral (regla de los 15: 15 g, reevaluar a los 15 min, repetir si persiste). En hipoglucemia severa con alteración de conciencia: glucosa al 10% IV 100 mL en bolo o glucagón 1 mg IM/SC. Educar al paciente y un familiar sobre datos de alarma y autoaplicación.','{"especialidad":"urgencias / endocrinología"}'),
('imss-718-tamizaje-complicaciones','GPC IMSS SS-718-15','27','Tamizaje anual de complicaciones de DM2','Al diagnóstico de DM2 y posteriormente anualmente realizar: examen oftalmológico con fondo de ojo dilatado, microalbuminuria (relación albumina/creatinina en orina al azar) y creatinina sérica con cálculo de TFGe, exploración de pies con monofilamento y diapasón, perfil de lípidos, y evaluación cardiovascular dirigida según riesgo.','{"especialidad":"endocrinología"}'),
('ada-2024-dm-gestacional-tamizaje','ADA Standards of Care 2024','S15','Tamizaje de diabetes gestacional','Realizar tamizaje de DM gestacional con curva de tolerancia oral a la glucosa de una etapa con carga de 75 g entre las semanas 24-28 de gestación en mujeres sin diagnóstico previo. Criterios diagnósticos (cualquiera basta): glucemia en ayuno ≥92 mg/dL, 1h ≥180 mg/dL, 2h ≥153 mg/dL. En mujeres con factores de riesgo, tamizar al primer contacto prenatal.','{"especialidad":"obstetricia / endocrinología","año":"2024"}'),
('ahaacc-2017-definicion-has','AHA/ACC Hypertension Guideline 2017','Tabla 6','Definición y categorías de HAS','TA normal: menor de 120/80 mmHg. Elevada: 120-129 sistólica y menor de 80 diastólica. HAS estadio 1: 130-139/80-89 mmHg. HAS estadio 2: ≥140/90 mmHg. Crisis hipertensiva: mayor de 180/120 mmHg, requiere evaluación urgente para descartar daño a órgano blanco.','{"especialidad":"cardiología","año":"2017"}'),
('ahaacc-2017-meta-ta','AHA/ACC Hypertension Guideline 2017','Sección 8','Meta de tensión arterial en adultos con HAS','Meta general menor de 130/80 mmHg en la mayoría de adultos con HAS, particularmente en pacientes con riesgo cardiovascular alto a 10 años ≥10%, DM, ERC, ASCVD o IC. En adultos mayores de 65 años evitar TA sistólica menor de 130 si causa hipotensión ortostática o caídas; individualizar.','{"especialidad":"cardiología","año":"2017"}'),
('imss-076-tratamiento-inicial','GPC IMSS SS-076-08','18','Tratamiento inicial farmacológico en HAS','Iniciar monoterapia en estadio 1 sin daño a órgano blanco con: IECA o ARA II (preferencia con DM, ERC, proteinuria, IC), calcio antagonista dihidropiridínico o tiazida en dosis baja. En estadio 2 o con riesgo alto, iniciar combinación de dos agentes preferentemente fija (IECA o ARA II + calcio antagonista o tiazida). Evitar combinación de IECA con ARA II por riesgo renal e hipotensión sin beneficio adicional.','{"especialidad":"cardiología"}'),
('ahaacc-2018-iam-stemi-aspirina','AHA/ACC STEMI Guideline 2013, focused update 2017','Sección 4','Manejo inicial de IAM con elevación del ST','Ante IAM con elevación del ST, administrar aspirina 162-325 mg vía oral masticada lo antes posible y activar el sistema de cateterismo cardiaco para angioplastia primaria con tiempo puerta-balón menor de 90 minutos. Si no hay acceso a hemodinamia en menos de 120 minutos, considerar fibrinolisis si no hay contraindicación. Doble antiagregación con aspirina + inhibidor P2Y12 (ticagrelor o clopidogrel).','{"especialidad":"cardiología / urgencias"}'),
('esc-ic-fer-tratamiento','ESC Heart Failure Guideline 2021','Tabla 13','Tratamiento farmacológico en IC con FEVI reducida','En insuficiencia cardiaca con fracción de eyección reducida (FEVI ≤40%) los cuatro pilares de tratamiento son: IECA o ARNI (sacubitrilo/valsartán preferible), betabloqueador (carvedilol, bisoprolol o metoprolol succinato), antagonista del receptor mineralocorticoide (espironolactona o eplerenona) e inhibidor SGLT2 (dapagliflozina o empagliflozina). Titular cada agente hasta la dosis máxima tolerada.','{"especialidad":"cardiología","año":"2021"}'),
('aha-acv-ventana-trombolisis','AHA/ASA Acute Ischemic Stroke 2019','Tabla 6','Trombolisis IV en ACV isquémico agudo','Alteplasa IV 0.9 mg/kg (máximo 90 mg) está indicada en ACV isquémico agudo dentro de las primeras 4.5 horas del inicio de síntomas en pacientes seleccionados sin contraindicaciones. La trombectomía mecánica está indicada en oclusión de arteria grande hasta 24 horas en pacientes con tejido cerebral salvable evaluado por imagen. Tiempo es cerebro: cada minuto sin reperfusión se pierden aproximadamente 1.9 millones de neuronas.','{"especialidad":"neurología / urgencias","año":"2019"}'),
('gina-2024-paso1-asma','GINA 2024','Box 3-5A','Tratamiento del asma en pasos 1-2','En adultos y adolescentes con asma se recomienda como tratamiento de mantenimiento y rescate del paso 1-2 corticoide inhalado en dosis baja más formoterol según necesidad (estrategia MART/AIR). NO se recomienda iniciar con beta-2 agonista de acción corta (SABA) solo, por incremento de exacerbaciones, hospitalizaciones y mortalidad asociado al uso aislado de SABA.','{"especialidad":"neumología","año":"2024"}'),
('gina-2024-exacerbacion-grave','GINA 2024','Box 4-3','Tratamiento de exacerbación grave de asma en urgencias','Ante exacerbación grave (FEV1 menor de 50% o SpO2 menor de 92% en aire ambiente, dificultad para hablar) administrar salbutamol nebulizado 5 mg cada 20 min por una hora, ipratropio nebulizado 0.5 mg cada 20 min por una hora, oxígeno suplementario para SpO2 ≥93-95%, prednisona 40-50 mg vía oral o hidrocortisona 200 mg IV, considerar magnesio sulfato 2 g IV en casos refractarios. Reevaluar a los 60 minutos.','{"especialidad":"neumología / urgencias","año":"2024"}'),
('gold-2024-categorias','GOLD 2024','Tabla 4.1','Categorización ABE de EPOC y tratamiento inicial','GOLD 2024 simplificó la clasificación a tres grupos: A (0-1 exacerbación leve, mMRC 0-1 / CAT menor de 10), B (0-1 exacerbación leve, mMRC ≥2 / CAT ≥10), y E (≥2 exacerbaciones moderadas o ≥1 hospitalización). Tratamiento inicial: A: broncodilatador (LABA o LAMA); B: LABA + LAMA combinación; E: LABA + LAMA, considerar agregar corticoide inhalado si eosinófilos ≥300 cél/μL.','{"especialidad":"neumología","año":"2024"}'),
('nice-tep-puntaje-wells','NICE NG158','1.1','Probabilidad clínica de tromboembolia pulmonar','Ante sospecha de TEP calcular escala de Wells de dos niveles. Probabilidad alta (Wells mayor de 4): solicitar angio-TC pulmonar inmediato; iniciar anticoagulación con HBPM mientras espera resultado si no hay contraindicación. Probabilidad baja (Wells ≤4): solicitar dímero-D; si negativo descarta TEP, si positivo continuar con angio-TC. En embarazadas considerar gammagrafía V/Q.','{"especialidad":"neumología / urgencias"}'),
('ssc-sepsis-hora-dorada','Surviving Sepsis Campaign 2021','Bundle 1h','Bundle de la primera hora en sepsis y shock séptico','Ante sospecha de sepsis o shock séptico, en la primera hora medir lactato sérico, obtener hemocultivos antes de antibióticos, iniciar antibiótico empírico de amplio espectro guiado por sospecha de foco, administrar cristaloides 30 mL/kg si hipotensión o lactato ≥4 mmol/L, e iniciar vasopresores (norepinefrina como primera línea) para mantener PAM ≥65 mmHg si la hipotensión persiste tras volumen.','{"especialidad":"urgencias / terapia intensiva","año":"2021"}'),
('ssc-norepinefrina-primera','Surviving Sepsis Campaign 2021','Rec. 25','Vasopresor inicial en shock séptico','Norepinefrina es el vasopresor de primera línea en shock séptico, iniciar 0.05-0.1 mcg/kg/min y titular para PAM ≥65 mmHg. Si la respuesta es inadecuada agregar vasopresina 0.03 U/min como segundo agente. Considerar epinefrina como tercer agente. La dopamina ya NO se recomienda excepto en bradicardia con bajo riesgo de taquiarritmia.','{"especialidad":"terapia intensiva","año":"2021"}'),
('aha-acls-paro-cardiaco','AHA ACLS 2020','Algoritmo 1','Algoritmo de paro cardiorrespiratorio en adulto','Iniciar RCP de alta calidad (100-120 compresiones/min, profundidad 5-6 cm, descompresión completa, minimizar interrupciones). Si ritmo desfibrilable (FV/TV sin pulso): desfibrilar 200 J bifásico, continuar RCP 2 min, epinefrina 1 mg IV cada 3-5 min tras la segunda descarga, considerar amiodarona 300 mg IV bolo. Si ritmo no desfibrilable (asistolia/AESP): RCP, epinefrina 1 mg IV cada 3-5 min, buscar y tratar causas reversibles (5H y 5T).','{"especialidad":"urgencias / cardiología","año":"2020"}'),
('atls-trauma-abcde','ATLS 10ª edición','Cap 1','Evaluación inicial en trauma — ABCDE','Aproximación primaria sistemática: A (vía aérea con control de columna cervical), B (ventilación: oxígeno suplementario, descartar neumotórax a tensión y hemotórax masivo), C (circulación con control de hemorragia: presión, torniquete, accesos vasculares y reposición con volumen y/o hemoderivados según escenario), D (déficit neurológico: Glasgow, pupilas), E (exposición y prevención de hipotermia). Reevaluar continuamente; no avanzar al siguiente paso sin resolver el anterior.','{"especialidad":"urgencias / trauma"}'),
('ssc-ninos-sepsis','Surviving Sepsis Pediatric 2020','Bundle','Bundle de sepsis pediátrica primera hora','En sepsis pediátrica con shock administrar cristaloides isotónicos en bolos de 10-20 mL/kg (hasta 40-60 mL/kg en la primera hora) si no hay datos de sobrecarga, iniciar antibiótico empírico en la primera hora, considerar epinefrina periférica si la hipotensión persiste tras 40 mL/kg de volumen, transfundir si hemoglobina menor de 7 g/dL en pacientes hemodinámicamente estables.','{"especialidad":"pediatría / urgencias","año":"2020"}'),
('kdigo-2024-erc-etapas','KDIGO ERC 2024','Tabla 2.1','Clasificación de enfermedad renal crónica','La ERC se estadifica por TFGe (G1 ≥90, G2 60-89, G3a 45-59, G3b 30-44, G4 15-29, G5 menor de 15 mL/min/1.73m²) Y por albuminuria (A1 menor de 30, A2 30-300, A3 mayor de 300 mg/g de creatinina urinaria). El pronóstico empeora conforme baja TFGe y/o sube albuminuria. ERC se confirma con persistencia mayor de 3 meses.','{"especialidad":"nefrología","año":"2024"}'),
('kdigo-2024-erc-tratamiento','KDIGO ERC 2024','Cap. 3','Pilares de tratamiento en ERC','Cuatro pilares conservadores en ERC: control de TA con IECA o ARA II (meta menor de 120/80 según evidencia reciente en algunos pacientes seleccionados, individualizar), inhibidor de SGLT2 si TFGe ≥20 mL/min/1.73m² (independientemente de DM), restricción de sodio menor de 2 g/día y estatina en mayores de 50 años. Finerenona en ERC con DM2 y albuminuria persistente.','{"especialidad":"nefrología","año":"2024"}'),
('aasld-hgnoa-tamizaje','AASLD MASLD 2023','Sección 4','Tamizaje de esteatosis hepática metabólica (MASLD)','En pacientes con DM2, obesidad o síndrome metabólico realizar tamizaje con FIB-4 (índice basado en edad, AST, ALT y plaquetas). FIB-4 menor de 1.3 descarta fibrosis avanzada en mayoría de pacientes; FIB-4 mayor de 2.67 sugiere fibrosis avanzada y amerita referencia a hepatología o evaluación con FibroScan / elastografía. Pérdida de peso 5-10% mejora histología hepática significativamente.','{"especialidad":"hepatología","año":"2023"}'),
('aga-erge-tratamiento','AGA Clinical Practice Update on GERD 2022','Sección 3','Tratamiento del reflujo gastroesofágico','Iniciar inhibidor de bomba de protones (omeprazol, pantoprazol, esomeprazol) una vez al día 30 minutos antes del desayuno por 8 semanas en ERGE con síntomas típicos. Si no hay respuesta, considerar dos tomas al día por 4-8 semanas adicionales. Endoscopia con biopsia si datos de alarma (disfagia, sangrado, pérdida de peso, anemia, mayor de 50 años con síntomas nuevos). Reducir dosis al mínimo eficaz a largo plazo.','{"especialidad":"gastroenterología","año":"2022"}'),
('acog-preeclampsia','ACOG Practice Bulletin 222','Sección 3','Criterios diagnósticos de preeclampsia','Diagnóstico de preeclampsia: TA ≥140/90 mmHg en dos ocasiones separadas por al menos 4 horas, después de la semana 20 en mujer previamente normotensa, MÁS proteinuria ≥300 mg en orina de 24h o relación proteína/creatinina ≥0.3 o tira reactiva ≥2+. En ausencia de proteinuria, diagnóstico se confirma con cualquier hallazgo grave: trombocitopenia, elevación de enzimas hepáticas, insuficiencia renal, edema pulmonar, síntomas neurológicos o visuales.','{"especialidad":"obstetricia"}'),
('imss-control-prenatal','GPC IMSS Control Prenatal','Tabla 2','Esquema de control prenatal en embarazo de bajo riesgo','Mínimo 5 consultas prenatales en embarazo de bajo riesgo: primera consulta antes de las 13 semanas, segunda entre 22-24, tercera entre 27-29, cuarta entre 33-35, quinta entre 38-40. En cada consulta: peso, TA, fondo uterino, frecuencia cardiaca fetal, movimientos fetales, signos de alarma, valoración nutricional y emocional. Suplementación con ácido fólico 400 mcg/día y hierro elemental 30-60 mg/día desde primera consulta.','{"especialidad":"obstetricia"}'),
('aap-bronquiolitis','AAP Bronchiolitis Guideline 2014','Sección 3','Manejo de bronquiolitis aguda en lactante','Bronquiolitis aguda en menores de 24 meses se diagnostica clínicamente; NO se recomienda solicitar radiografía de tórax, hemograma o virología de rutina. NO se recomienda usar broncodilatadores (salbutamol), corticoides, epinefrina nebulizada ni antibióticos de rutina. Pilares: oxígeno si SpO2 menor de 90%, hidratación oral o enteral, lavados nasales con solución salina. Considerar hospitalización si dificultad respiratoria moderada-grave o pobre tolerancia oral.','{"especialidad":"pediatría","año":"2014"}'),
('aap-fiebre-sin-foco','AAP Febrile Infant 2021','Tabla 3','Evaluación de fiebre sin foco en lactante menor de 60 días','En lactante menor de 21 días con fiebre ≥38°C realizar evaluación completa: hemocultivo, urocultivo, citoquímico y cultivo de LCR, iniciar antibiótico empírico (ampicilina + cefotaxima o gentamicina) y hospitalizar. En 22-28 días considerar evaluación selectiva guiada por procalcitonina menor de 0.5 ng/mL y biomarcadores. En 29-60 días con apariencia tóxica también evaluación completa; en apariencia bien estratificar con biomarcadores.','{"especialidad":"pediatría","año":"2021"}'),
('dsm5tr-depresion-criterios','DSM-5-TR (APA 2022)','Cap. Depresión','Criterios diagnósticos de trastorno depresivo mayor','Cinco o más de los siguientes síntomas durante al menos dos semanas, con al menos uno de los dos primeros: 1) ánimo deprimido la mayor parte del día casi todos los días; 2) marcada disminución de interés o placer (anhedonia); 3) cambio significativo de peso/apetito; 4) insomnio o hipersomnia; 5) agitación o enlentecimiento psicomotor; 6) fatiga o pérdida de energía; 7) sentimientos de inutilidad o culpa excesiva; 8) disminución de concentración; 9) pensamientos recurrentes de muerte o ideación suicida. Causan deterioro funcional significativo y no son explicados por otra condición.','{"especialidad":"psiquiatría","año":"2022"}'),
('nice-depresion-tratamiento','NICE NG222 Depression in adults','1.4','Tratamiento inicial de depresión en adulto','En depresión leve a moderada considerar TCC, terapia de resolución de problemas o activación conductual como primera línea. En depresión moderada a grave ofrecer combinación de psicoterapia más antidepresivo: ISRS de primera línea (sertralina, escitalopram, fluoxetina); evaluar respuesta a las 4 semanas. NO usar benzodiacepinas como tratamiento de fondo. Evaluar riesgo suicida en cada consulta inicialmente. Continuar tratamiento al menos 6 meses tras remisión.','{"especialidad":"psiquiatría","año":"2022"}'),
('phq9-tamizaje','USPSTF/PHQ-9','Instrumento','Tamizaje de depresión con PHQ-9','PHQ-9 es instrumento validado en español para tamizaje de depresión en atención primaria. Puntaje 0-4: mínimo o ninguno; 5-9: depresión leve; 10-14: moderada; 15-19: moderadamente severa; 20-27: severa. Punto de corte ≥10 con sensibilidad 88% y especificidad 88% para depresión mayor. La pregunta 9 evalúa ideación suicida y requiere intervención inmediata si responde 1, 2 o 3.','{"especialidad":"psiquiatría / atención primaria"}'),
('idsa-nac-tratamiento','ATS/IDSA NAC 2019','Sección 5','Tratamiento empírico de neumonía adquirida en comunidad ambulatoria','En NAC ambulatoria sin comorbilidades ni factores de riesgo de resistencia: amoxicilina 1 g cada 8 horas vía oral o doxiciclina 100 mg cada 12 horas o azitromicina 500 mg el día 1, luego 250 mg días 2-5. En NAC ambulatoria con comorbilidades (EPOC, DM, IC, ERC, neoplasia): beta-lactámico (amoxicilina-clavulánico 875/125 mg c/12h o cefuroxima 500 mg c/12h) MÁS macrólido (azitromicina) o monoterapia con fluoroquinolona respiratoria (levofloxacino o moxifloxacino).','{"especialidad":"infectología / neumología","año":"2019"}'),
('who-tuberculosis-tratamiento','WHO TB Guidelines 2022','Cap. 4','Tratamiento de tuberculosis pulmonar sensible','Esquema estándar de 6 meses para TB pulmonar sensible: fase intensiva de 2 meses con isoniazida, rifampicina, pirazinamida y etambutol (HRZE) seguida de fase de continuación de 4 meses con isoniazida y rifampicina (HR). Recientemente WHO recomienda esquema corto alternativo de 4 meses con rifapentina, isoniazida, pirazinamida y moxifloxacino en pacientes seleccionados ≥12 años. Tratamiento siempre supervisado (DOT/DOTS).','{"especialidad":"infectología","año":"2022"}'),
('cdc-prep-vih','CDC PrEP Clinical Practice Guideline 2021','Sección 3','Profilaxis pre-exposición para VIH (PrEP)','PrEP indicada en adultos sexualmente activos con VIH negativo y riesgo sustancial de adquisición. Opciones: TDF/FTC (Truvada) 1 tableta diaria, TAF/FTC (Descovy) 1 tableta diaria en HSH o mujeres trans, o cabotegravir inyectable cada 2 meses. Confirmar VIH negativo antes del inicio y cada 3 meses durante uso. Función renal y screening de ITS cada 3-6 meses. PrEP reduce el riesgo de transmisión sexual de VIH en 99% cuando se toma según lo prescrito.','{"especialidad":"infectología","año":"2021"}'),
('beers-2023-anticolinergicos','AGS Beers Criteria 2023','Tabla 2','Medicamentos potencialmente inadecuados en adulto mayor','Evitar en adultos ≥65 años por riesgo elevado de eventos adversos: antihistamínicos de primera generación (difenhidramina, hidroxizina) por efecto anticolinérgico; benzodiacepinas (excepto situaciones específicas) por caídas y deterioro cognitivo; AINEs no selectivos crónicos por riesgo GI y renal; amitriptilina por carga anticolinérgica; sulfonilureas de larga duración (glibenclamida) por hipoglucemia prolongada; relajantes musculares centrales (ciclobenzaprina) por sedación y caídas.','{"especialidad":"geriatría","año":"2023"}'),
('nice-caidas-adulto-mayor','NICE CG161','1.2','Evaluación y prevención de caídas en adulto mayor','En adulto ≥65 años indagar antecedente de caídas en el último año en cada consulta. En quienes refieren al menos una caída, dificultades de equilibrio o marcha: evaluación multifactorial con prueba Get-Up-and-Go cronometrada (mayor de 12 segundos es anormal), evaluación visual, polifarmacia, ortostatismo, calzado, hipoglucemia, ECG si sospecha de síncope. Intervenciones eficaces: ejercicio de fuerza y equilibrio (Tai Chi, Otago), revisión farmacológica, ajuste domiciliario.','{"especialidad":"geriatría"}'),
('asco-anemia-ferropenica','ASH/ACOG Iron Deficiency','Recomendaciones','Diagnóstico y tratamiento de anemia ferropénica','Diagnóstico: hemoglobina menor de 12 g/dL en mujeres no embarazadas y menor de 13 g/dL en hombres, con ferritina menor de 30 ng/mL. En embarazo umbral hemoglobina menor de 11 g/dL en primer y tercer trimestre, menor de 10.5 g/dL en segundo trimestre. Tratamiento oral: sulfato ferroso 60-120 mg de hierro elemental cada 24-48 horas (mejor absorción que diario) lejos de alimentos y calcio. Hierro IV (carboximaltosa férrica, sacarosa férrica) si intolerancia oral, sangrado GI activo, malabsorción o tercer trimestre con anemia significativa.','{"especialidad":"hematología"}'),
('acr-ar-tratamiento','ACR Rheumatoid Arthritis 2021','Recomendaciones','Tratamiento inicial de artritis reumatoide','Iniciar metotrexato monoterapia 7.5-15 mg vía oral semanal con ácido fólico 1 mg/día (suplemento), titular hasta 25 mg semanal en 2-3 meses. Si DAS28 mayor de 3.2 a los 3-6 meses agregar un segundo DMARD convencional (sulfasalazina, leflunomida, hidroxicloroquina) o un biológico (inhibidor de TNF, abatacept, rituximab) o inhibidor de JAK. Evaluar respuesta cada 3 meses. Vigilar pruebas hepáticas, hematológicas y signos de infección.','{"especialidad":"reumatología","año":"2021"}'),
('nom-004-nota-medica-elementos','NOM-004-SSA3-2012','6.2','Elementos mínimos de la nota médica','La nota médica debe contener fecha y hora, signos vitales, padecimiento actual, exploración física por aparatos y sistemas, resultados relevantes de estudios, diagnósticos o problemas clínicos, pronóstico, tratamiento e indicaciones, así como nombre completo y firma del médico responsable. La nota de evolución incluye también valoración del estado actual y plan terapéutico actualizado.','{"categoría":"regulación"}'),
('nom-004-consentimiento-informado','NOM-004-SSA3-2012','10.1','Consentimiento informado','Los procedimientos diagnósticos y terapéuticos considerados de alto riesgo requieren consentimiento informado por escrito, firmado por el paciente o su representante legal y dos testigos. Debe contener nombre del establecimiento, nombre y firma del paciente, acto autorizado, riesgos y beneficios, alternativas y nombre y firma del médico. Forma parte del expediente clínico.','{"categoría":"regulación"}'),
('nom-004-receta-elementos','NOM-004-SSA3-2012','8.6','Elementos de la receta médica','La receta médica debe incluir nombre, denominación genérica del medicamento, presentación, dosis, vía de administración, frecuencia y duración del tratamiento, firma autógrafa del médico, cédula profesional, fecha de emisión y nombre del paciente. Para estupefacientes y psicotrópicos se requiere receta especial con código de barras (recetario oficial).','{"categoría":"regulación"}'),
('nom-015-dm-control','NOM-015-SSA2-2010','8.2','Control metabólico en diabetes según NOM mexicana','Metas de control glucémico en DM2 según NOM-015 ajustadas a contexto mexicano: HbA1c menor de 7%, glucemia en ayuno 70-130 mg/dL, glucemia postprandial menor de 140 mg/dL, TA menor de 130/80 mmHg, LDL menor de 100 mg/dL (menor de 70 mg/dL si ASCVD), triglicéridos menor de 150 mg/dL, IMC menor de 25 kg/m². Evaluación trimestral de control, anual de complicaciones.','{"categoría":"regulación"}'),
('nom-030-has-clasificacion','NOM-030-SSA2-2009','Tabla 1','Clasificación de HAS según NOM mexicana','Clasificación de la NOM-030 vigente: TA óptima menor de 120/80 mmHg; normal alta 130-139/85-89 mmHg; HAS estadio 1: 140-159/90-99; HAS estadio 2: 160-179/100-109; HAS estadio 3: ≥180/110 mmHg. Diagnóstico requiere TA elevada en dos o más visitas, en al menos dos mediciones por consulta. Considera AHA/ACC 2017 más estricta cuando aplique a juicio clínico.','{"categoría":"regulación"}'),
('nom-024-interoperabilidad','NOM-024-SSA3-2012','Cap. 6','Sistemas de información en salud — interoperabilidad','Los establecimientos de salud deben usar sistemas de información que cumplan con: interoperabilidad mediante mensajes HL7, identificadores únicos del paciente (CURP), confidencialidad por roles, respaldo automatizado, trazabilidad de accesos, almacenamiento mínimo de 5 años para adultos y hasta la mayoría de edad más 5 años en menores.','{"categoría":"regulación"}'),
('nom-220-farmacovigilancia','NOM-220-SSA1-2016','Cap. 5','Reporte de sospecha de reacción adversa a medicamentos','Todo profesional de la salud debe reportar a Farmacovigilancia COFEPRIS sospechas de reacciones adversas medicamentosas graves (que requieran hospitalización, prolonguen estancia, ocasionen incapacidad o muerte) en máximo 15 días naturales. Reacciones no graves: en máximo 30 días. Formato electrónico vía e-Reporting o formulario oficial. Identificar paciente con iniciales, edad y sexo (sin datos identificables completos).','{"categoría":"regulación"}'),
('lgs-2026-expediente-electronico','Reforma LGS 2026','Art. 134 bis','Expediente clínico electrónico obligatorio','Los establecimientos de atención médica privados y públicos deberán contar con expediente clínico electrónico interoperable que cumpla los lineamientos federales de seguridad de datos personales en salud y permita intercambio entre niveles de atención. Plazo escalonado: 2026 hospitales segundo y tercer nivel; 2027 primer nivel y consultorios privados con más de 3 médicos; 2028 todos.','{"categoría":"regulación","año":"2026"}'),
('uspstf-cancer-mama-tamizaje','USPSTF Mamografía 2024','Recomendación B','Tamizaje de cáncer de mama','Mamografía cada 2 años en mujeres de 40 a 74 años con riesgo promedio (recomendación B, actualizada en 2024 que bajó la edad inicial de 50 a 40 años). En mujeres con riesgo elevado (antecedente familiar primer grado, BRCA, radiación torácica) considerar inicio temprano y/o resonancia magnética complementaria. Educar sobre densidad mamaria y limitaciones de mamografía en mamas densas.','{"especialidad":"ginecología / prevención","año":"2024"}'),
('uspstf-cancer-colon-tamizaje','USPSTF Cáncer colorrectal 2021','Recomendación B','Tamizaje de cáncer colorrectal','Tamizaje de cáncer colorrectal en todos los adultos entre 45 y 75 años con riesgo promedio. Opciones: sangre oculta en heces inmunoquímica (FIT) anual, FIT-DNA cada 1-3 años, sigmoidoscopia cada 5 años, colonoscopia cada 10 años, colonoscopia virtual cada 5 años. La colonoscopia sigue siendo gold standard. En 76-85 años decisión individualizada con paciente.','{"especialidad":"gastroenterología / prevención","año":"2021"}'),
('imss-tamizaje-cacu','GPC IMSS Cáncer Cervicouterino','Recomendación 4','Tamizaje de cáncer cervicouterino','Citología cervical anual en mujeres de 25 a 64 años. Si dos citologías anuales consecutivas son negativas, continuar cada 3 años. Alternativa: prueba de VPH cada 5 años en mayores de 30 años. Vacunación contra VPH en niñas y niños de 11 años (esquema 2 dosis menor de 15 años, 3 dosis ≥15 años). Coinfección VIH requiere tamizaje más frecuente.','{"especialidad":"ginecología / prevención"}'),
('who-anticoncepcion-emergencia','WHO Family Planning 2022','Cap. 7','Anticoncepción de emergencia','Levonorgestrel 1.5 mg vía oral dosis única dentro de las primeras 72 horas tras relación sin protección (eficacia decrece con el tiempo, mejor en primeras 12 h). Acetato de ulipristal 30 mg hasta 120 horas post-coito (más eficaz que levonorgestrel después de 72 h). DIU de cobre insertado dentro de 5 días post-coito es el método más eficaz (>99%) y deja anticoncepción a largo plazo. NO es abortiva: actúa previniendo o retrasando la ovulación.','{"especialidad":"ginecología","año":"2022"}'),
('ssa-mx-vacunas-adulto','Esquema Nacional de Vacunación Adulto MX 2024','Tabla','Vacunación recomendada en adultos en México','Adultos en México deben tener: Td (tétanos/difteria) refuerzo cada 10 años, hepatitis B en grupos de riesgo, SR/SRP en mujeres en edad fértil susceptibles, influenza anual estacional (especialmente ≥60 años, embarazadas, comorbilidades), neumococo (PCV13 + PPSV23 con esquema secuencial en ≥60 años o factores de riesgo), Tdpa en cada embarazo (semana 27-36), VPH si menor de 26 años, herpes zóster recombinante en ≥50 años, COVID-19 según recomendación vigente.','{"especialidad":"prevención","año":"2024"}')
on conflict (id) do update set
  source = excluded.source,
  page = excluded.page,
  title = excluded.title,
  content = excluded.content,
  meta = excluded.meta;
