-- LitienGuard — Corpus expansion (Hito 6)
-- +100 chunks across endocrinology, cardiology, neurology, gastroenterology,
-- oncology, dermatology, ophthalmology, pediatrics, mental health, geriatrics,
-- gynecology, infectious diseases, and procedures.
-- All sources are public, verifiable clinical guidelines or society
-- consensus statements. Content is paraphrased — never verbatim copy of
-- copyrighted synthesis tools (UpToDate, NEJM, JAMA).

insert into public.cerebro_chunks (id, source, page, title, content, meta) values

-- ═══ Endocrinología (extensión) ═══════════════════════════════════════════
('ata-2024-hipotiroidismo-subclinico','ATA Thyroid Disorders 2024','Recomendación 12','Hipotiroidismo subclínico — cuándo tratar','En hipotiroidismo subclínico se recomienda iniciar levotiroxina si TSH ≥10 mUI/L confirmada en segunda determinación. Entre 4.5-10 mUI/L, considerar tratamiento en pacientes menor de 65 años con síntomas o anti-TPO positivos, en mujeres con deseo gestacional o embarazadas, y si existe bocio. En mayores de 65 años con TSH menor de 10 sin síntomas, observación con seguimiento en 6-12 meses.','{"especialidad":"endocrinología","año":"2024"}'),
('ata-2024-hipertiroidismo','ATA Thyroid 2024','Recomendación 21','Tratamiento de hipertiroidismo por enfermedad de Graves','Tres opciones de tratamiento en enfermedad de Graves: tionamidas (metimazol 10-30 mg/día como primera línea, propiltiouracilo en primer trimestre de embarazo y crisis tirotóxica), yodo radiactivo (I-131) y tiroidectomía total. Metimazol por 12-18 meses logra remisión en 30-50%. Vigilar agranulocitosis y hepatotoxicidad. En crisis tirotóxica: propiltiouracilo, betabloqueador (propranolol), yodo (solución de Lugol) y corticoide.','{"especialidad":"endocrinología","año":"2024"}'),
('ada-2024-insulinoterapia-dm2','ADA Standards of Care 2024','S9.40','Inicio de insulinoterapia en DM2','Iniciar insulina basal (NPH, glargina o detemir) en DM2 cuando HbA1c mayor de 10% al diagnóstico, glucemia mayor de 300 mg/dL, síntomas catabólicos, o falla con triple terapia oral. Dosis inicial 0.1-0.2 U/kg/día por la noche, titular cada 3 días con incrementos de 2 U según glucemia de ayuno objetivo. Agregar insulina prandial si HbA1c no logra meta tras optimización basal.','{"especialidad":"endocrinología","año":"2024"}'),
('ada-2024-cetoacidosis','ADA Diabetic Emergencies 2024','Tabla 1','Manejo de cetoacidosis diabética','Diagnóstico CAD: glucemia mayor de 250 mg/dL, pH menor de 7.30, HCO3 menor de 18, cetonemia/cetonuria, anion gap mayor de 12. Manejo: reposición hídrica con SS 0.9% 1-1.5 L primera hora, después ajustar; insulina IV en infusión 0.1 U/kg/h tras carga 0.1 U/kg; corrección de potasio antes de insulina si K menor de 3.3; bicarbonato solo si pH menor de 6.9; identificar y tratar precipitante (infección, omisión de dosis, IAM).','{"especialidad":"urgencias / endocrinología","año":"2024"}'),
('ada-2024-estado-hiperosmolar','ADA Diabetic Emergencies 2024','Tabla 2','Estado hiperosmolar hiperglucémico','Criterios diagnósticos: glucemia mayor de 600 mg/dL, osmolaridad sérica mayor de 320 mOsm/kg, ausencia de cetoacidosis significativa, pH mayor de 7.30, deshidratación severa. Mortalidad 5-20%, mayor en ancianos. Manejo: reposición vigorosa de volumen (déficit estimado 8-12 L), insulina IV a dosis menor que en CAD, corrección lenta de hipernatremia para evitar mielinólisis pontina, vigilancia neurológica continua.','{"especialidad":"urgencias / endocrinología","año":"2024"}'),
('nof-2024-osteoporosis','NOF Clinician Guide 2024','Sección 5','Evaluación y tratamiento de osteoporosis','Indicaciones de DEXA: mujeres ≥65 años, hombres ≥70 años, posmenopáusicas con factores de riesgo, fracturas por fragilidad. T-score ≤-2.5 = osteoporosis; -2.5 a -1.0 = osteopenia. Iniciar tratamiento farmacológico si T-score ≤-2.5, fractura por fragilidad de cadera o vértebra, o FRAX a 10 años ≥3% cadera o ≥20% mayor. Primera línea: alendronato 70 mg semanal vía oral o ácido zoledrónico 5 mg IV anual. Calcio 1200 mg/día + vitamina D 800-1000 UI/día. Reevaluar tratamiento a los 5 años.','{"especialidad":"endocrinología / reumatología","año":"2024"}'),
('endocrine-hiponatremia','Endocrine Society Hyponatremia 2014','Tabla 3','Manejo de hiponatremia según severidad','Hiponatremia severa (Na menor de 125 mEq/L) con síntomas neurológicos: bolo de SS 3% 100-150 mL IV en 10 min, repetir hasta 2 veces, corregir Na máximo 8-10 mEq/L en 24 horas para evitar mielinólisis pontina. Hiponatremia leve a moderada asintomática: restricción hídrica menor de 800 mL/día, identificar causa (SIADH, deshidratación, IC, cirrosis, hipotiroidismo). Tolvaptán en SIADH crónica con respuesta inadecuada a restricción.','{"especialidad":"endocrinología / urgencias","año":"2014"}'),
('ata-2017-tiroides-embarazo','ATA Thyroid in Pregnancy 2017','Tabla 4','Manejo de hipotiroidismo en embarazo','TSH objetivo en embarazo: primer trimestre menor de 2.5 mUI/L, segundo-tercer trimestre menor de 3.0 mUI/L. En mujer con hipotiroidismo conocido aumentar dosis de levotiroxina 25-30% al confirmar embarazo y monitorizar TSH cada 4 semanas hasta semana 20, luego cada trimestre. Hipotiroidismo subclínico con anti-TPO positivos requiere tratamiento. Posparto retornar a dosis pregestacional.','{"especialidad":"endocrinología / obstetricia","año":"2017"}'),
('ncep-atp3-sindrome-metabolico','NCEP ATP III modificado 2005','Criterios','Diagnóstico de síndrome metabólico','Síndrome metabólico requiere 3 o más de: 1) circunferencia abdominal ≥90 cm en hombres o ≥80 cm en mujeres (criterios IDF para latinos); 2) triglicéridos ≥150 mg/dL o tratamiento; 3) HDL menor de 40 mg/dL en hombres o menor de 50 mg/dL en mujeres; 4) TA ≥130/85 mmHg o tratamiento antihipertensivo; 5) glucemia en ayuno ≥100 mg/dL o tratamiento. Manejo: pérdida de peso 5-10%, ejercicio aeróbico 150 min/semana, dieta mediterránea.','{"especialidad":"endocrinología / atención primaria"}'),

-- ═══ Cardiología (extensión) ══════════════════════════════════════════════
('esc-2024-fa-cha2ds2vasc','ESC Atrial Fibrillation 2024','Tabla 8','Escala CHA2DS2-VASc para anticoagulación en fibrilación auricular','Calcular CHA2DS2-VASc: ICC (1), HAS (1), edad ≥75 (2), DM (1), ACV/AIT previo (2), enfermedad vascular (1), edad 65-74 (1), sexo femenino (1). Hombre con score ≥1 o mujer con ≥2 (excluyendo sexo): anticoagulación oral recomendada. Primera línea: anticoagulante oral directo (apixabán, rivaroxabán, dabigatrán, edoxabán) sobre warfarina excepto valvulopatía mitral severa o prótesis mecánica donde warfarina es obligada.','{"especialidad":"cardiología","año":"2024"}'),
('esc-2024-fa-hasbled','ESC AF 2024','Tabla 9','Escala HAS-BLED de riesgo de sangrado en anticoagulación','HAS-BLED: HAS (1), función hepática/renal alterada (1 c/u), ACV (1), historia de sangrado (1), INR lábil (1), edad mayor de 65 (1), fármacos/alcohol (1 c/u). Score ≥3 implica riesgo alto pero NO contraindica anticoagulación: identifica factores modificables (control de TA, suspender AINE, alcohol) para reducir riesgo.','{"especialidad":"cardiología","año":"2024"}'),
('ahaacc-2014-nstemi','AHA/ACC NSTEMI 2014','Sección 4','Estratificación de SCA sin elevación del ST','Estratificación TIMI o GRACE para SCA-SEST. Estrategia invasiva temprana (menor de 24h) si TIMI ≥4, troponina alta, cambios dinámicos ST/T, insuficiencia cardiaca, inestabilidad hemodinámica o angina recurrente. Manejo: aspirina + inhibidor P2Y12 (ticagrelor preferido sobre clopidogrel), anticoagulación con HBPM o fondaparinux, estatina alta intensidad, betabloqueador si no hay contraindicación, IECA en disfunción ventricular o DM.','{"especialidad":"cardiología / urgencias","año":"2014"}'),
('ahaacc-2018-estatinas','AHA/ACC Cholesterol 2018','Tabla 4','Estatinas de alta intensidad en prevención','Estatinas de alta intensidad (reducción LDL ≥50%): atorvastatina 40-80 mg/día o rosuvastatina 20-40 mg/día. Indicadas en: prevención secundaria (ASCVD establecida), LDL ≥190 mg/dL, DM con edad 40-75 + riesgo alto, prevención primaria con riesgo cardiovascular a 10 años ≥20%. Considerar ezetimibe 10 mg/día si meta no alcanzada. Inhibidores PCSK9 (evolocumab, alirocumab) en pacientes de muy alto riesgo con LDL persistentemente elevado.','{"especialidad":"cardiología","año":"2018"}'),
('esc-2019-ldl-metas','ESC/EAS Dyslipidemia 2019','Tabla 3','Metas de LDL por categoría de riesgo cardiovascular','Riesgo muy alto (ASCVD documentada, DM con daño a órgano blanco, ERC severa): LDL menor de 55 mg/dL y reducción ≥50% del basal. Riesgo alto (DM sin daño con duración ≥10 años, ERC moderada, FRS 5-10%): LDL menor de 70 mg/dL. Riesgo moderado: LDL menor de 100 mg/dL. Riesgo bajo: LDL menor de 116 mg/dL. Re-evaluar a 4-12 semanas tras inicio o ajuste.','{"especialidad":"cardiología","año":"2019"}'),
('esc-2015-pericarditis','ESC Pericardial Diseases 2015','Recomendación 16','Pericarditis aguda — tratamiento de primera línea','Tratamiento de primera línea: AINE (ibuprofeno 600 mg c/8h o ácido acetilsalicílico 750-1000 mg c/8h) por 1-2 semanas con reducción gradual MÁS colchicina 0.5 mg/día (menor de 70 kg) o 0.5 mg c/12h (≥70 kg) por 3 meses. Colchicina reduce recurrencias y mejora respuesta. Restringir ejercicio. Evitar corticoides salvo etiología específica (autoinmune, urémica) por mayor recurrencia.','{"especialidad":"cardiología","año":"2015"}'),
('aha-2007-endocarditis-profilaxis','AHA Endocarditis Prophylaxis 2007','Tabla 3','Profilaxis antibiótica de endocarditis infecciosa','Profilaxis solo para pacientes con condiciones cardíacas de muy alto riesgo: prótesis valvular, endocarditis previa, cardiopatía congénita cianótica no reparada, primeros 6 meses post-reparación con material protésico, valvulopatía en trasplante cardíaco. Procedimientos: dentales con manipulación gingival/periapical, broncoscopia con biopsia, drenaje absceso. Régimen: amoxicilina 2 g VO 30-60 min antes (clindamicina 600 mg si alergia). NO indicada para procedimientos GI o GU rutinarios.','{"especialidad":"cardiología / infectología","año":"2007"}'),
('esc-2023-ic-fep','ESC HF preserved 2023','Sección 7','IC con FEVI preservada — tratamiento','IC con FEVI ≥50% (HFpEF): iSGLT2 (empagliflozina o dapagliflozina) reducen hospitalización por IC y muerte cardiovascular (estudios EMPEROR-Preserved y DELIVER); incluir como pilar de tratamiento. Diuréticos para control de congestión. Manejo agresivo de comorbilidades: HAS (meta menor de 130/80), DM2, FA, obesidad, anemia, ERC. Espironolactona en pacientes seleccionados con BNP elevado.','{"especialidad":"cardiología","año":"2023"}'),
('aha-acls-bradicardia','AHA ACLS Bradycardia 2020','Algoritmo','Algoritmo de bradicardia sintomática','Si bradicardia (FC menor de 50) con hipotensión, alteración mental aguda, signos de shock, dolor torácico isquémico o IC: atropina 1 mg IV cada 3-5 min (máximo 3 mg). Si refractaria: marcapaso transcutáneo, dopamina 5-20 mcg/kg/min o epinefrina 2-10 mcg/min. Buscar y tratar causa (medicamentos como betabloqueadores o calcio antagonistas, isquemia, hipoxia, hiperkalemia). Consultar cardiología para marcapaso definitivo si bloqueo AV alto grado.','{"especialidad":"urgencias / cardiología","año":"2020"}'),

-- ═══ Neurología ═══════════════════════════════════════════════════════════
('ahs-2021-migrana-aguda','American Headache Society 2021','Recomendación 3','Tratamiento agudo de migraña','Primera línea oral: triptán (sumatriptán 50-100 mg, rizatriptán 10 mg) más AINE (naproxeno 500 mg, ibuprofeno 600 mg) si crisis moderada-severa. En crisis leve probar AINE solo o paracetamol. Gepants (rimegepant, ubrogepant) y lasmiditán como alternativas si contraindicación a triptanes (ASCVD, ACV previo). Tratar a los primeros síntomas, evitar uso ≥10-15 días/mes para no inducir cefalea por abuso de medicamentos.','{"especialidad":"neurología","año":"2021"}'),
('ahs-2021-migrana-profilaxis','American Headache Society 2021','Recomendación 7','Profilaxis de migraña','Indicar profilaxis si ≥4 días de migraña al mes, crisis severas o refractarias, o uso excesivo de tratamiento agudo. Primera línea oral: propranolol 80-240 mg/día, topiramato 50-100 mg/día, amitriptilina 25-150 mg/día, candesartán 16 mg/día. Inyectable: toxina botulínica A (en migraña crónica) o anticuerpo monoclonal anti-CGRP (erenumab, fremanezumab, galcanezumab) en falla a 2 líneas orales. Evaluar respuesta a las 8-12 semanas.','{"especialidad":"neurología","año":"2021"}'),
('nice-ng217-epilepsia','NICE NG217 Epilepsy 2022','Sección 4','Manejo de primera crisis convulsiva','Tras primera crisis tónico-clónica: estudio con RM cerebral y EEG. NO iniciar antiepiléptico tras crisis única no provocada salvo factores de riesgo de recurrencia (lesión estructural, EEG anormal, antecedente familiar). Inicio de fármaco con segunda crisis. Primera línea: levetiracetam o lamotrigina (focal y generalizada), ácido valproico (generalizada — evitar en mujeres edad fértil). Monoterapia primero; combinar solo si falla.','{"especialidad":"neurología","año":"2022"}'),
('ncs-2016-estado-epileptico','Neurocritical Care Society 2016','Algoritmo','Estado epiléptico — manejo escalonado','Estado epiléptico: crisis ≥5 min o crisis recurrentes sin recuperación de conciencia entre ellas. Manejo: vía aérea, oxígeno, accesos IV, glucemia capilar. Primera línea: lorazepam 4 mg IV o diazepam 10 mg IV o midazolam 10 mg IM si no hay acceso. Segunda línea: levetiracetam 60 mg/kg IV (máximo 4.5 g) o fenitoína 20 mg/kg IV o ácido valproico 40 mg/kg IV. Tercera línea: intubación y anestesia con propofol o midazolam continuo, traslado a UTI.','{"especialidad":"neurología / urgencias","año":"2016"}'),
('mds-2018-parkinson','Movement Disorder Society 2018','Recomendación','Diagnóstico y tratamiento inicial de Parkinson','Criterios clínicos MDS: parkinsonismo (bradicinesia + temblor de reposo o rigidez) con respuesta sostenida a levodopa, sin signos de alerta para parkinsonismo atípico. Tratamiento inicial individualizado: levodopa/carbidopa en mayores de 65 años o discapacidad significativa, agonistas dopaminérgicos (pramipexol, ropinirol) en menor de 65 años para retrasar discinesias, inhibidores MAO-B (rasagilina, selegilina) en síntomas leves. Iniciar con dosis bajas y titular según respuesta.','{"especialidad":"neurología","año":"2018"}'),
('aha-2019-acv-prevencion-secundaria','AHA/ASA Secondary Stroke Prevention 2021','Tabla 9','Prevención secundaria tras ACV isquémico','Tras ACV isquémico no cardioembólico: antiagregación con aspirina 81-325 mg/día o clopidogrel 75 mg/día (combinación corto plazo 21-90 días en ACV menor o AIT alto riesgo), estatina alta intensidad (objetivo LDL menor de 70 mg/dL), control de TA (menor de 130/80 mmHg), control glucémico, cesación de tabaco. Si origen cardioembólico (FA): anticoagulación oral. Endarterectomía o stent carotídeo si estenosis sintomática 70-99%.','{"especialidad":"neurología","año":"2021"}'),
('mcdonald-2017-em','McDonald Criteria 2017','Tabla 2','Diagnóstico de esclerosis múltiple','Criterios McDonald 2017 para EM remitente-recurrente: ≥2 episodios con ≥2 lesiones objetivas; o ≥2 episodios con 1 lesión + diseminación en espacio (DIS); o 1 episodio con ≥2 lesiones + diseminación en tiempo (DIT); o 1 episodio con 1 lesión + DIS + DIT. Bandas oligoclonales en LCR pueden sustituir DIT. RM con secuencias T2/FLAIR y captación con gadolinio. Diagnóstico diferencial: neuromielitis óptica (anti-AQP4), MOG, vasculitis.','{"especialidad":"neurología","año":"2017"}'),
('aan-2022-neuropatia-diabetica','AAN Diabetic Neuropathy 2022','Recomendación','Manejo de neuropatía diabética dolorosa','Primera línea para dolor neuropático en DM: pregabalina (75-300 mg c/12h), gabapentina (300-1200 mg c/8h), duloxetina (60-120 mg/día) o antidepresivo tricíclico (amitriptilina 25-100 mg en la noche). Combinaciones razonables si monoterapia insuficiente. Tratamientos no farmacológicos: control glucémico estricto, ejercicio aeróbico. Tópicos: capsaicina 8% parches en dolor localizado.','{"especialidad":"neurología","año":"2022"}'),
('vppb-dix-hallpike','AAO-HNS BPPV 2017','Maniobra','Vértigo posicional paroxístico benigno','Diagnóstico con maniobra Dix-Hallpike: paciente sentado, girar cabeza 45° a un lado, acostar rápidamente con cabeza colgando 30° fuera de la mesa; observar nistagmus rotacional con latencia de segundos, fatiga. Tratamiento: maniobra de Epley (canalitiasis posterior — más frecuente). Educar al paciente: evitar movimientos bruscos por 48h tras maniobra. Recurrencia 15-20%/año; reentrenar con maniobras caseras (Brandt-Daroff).','{"especialidad":"otorrinolaringología / neurología","año":"2017"}'),

-- ═══ Gastroenterología ════════════════════════════════════════════════════
('aasld-hcv-2024','AASLD/IDSA HCV 2024','Recomendación','Tratamiento de hepatitis C crónica','Tratamiento universal recomendado para toda hepatitis C crónica (genotipos 1-6). Esquemas pangenotípicos primera línea: glecaprevir/pibrentasvir 8 semanas (12 si cirrosis compensada) o sofosbuvir/velpatasvir 12 semanas. Tasa de respuesta virológica sostenida mayor de 95%. No requiere genotipificación rutinaria con regímenes pangenotípicos. Evaluar fibrosis con FIB-4 o FibroScan; cirrosis avanzada Child B/C amerita centro especializado.','{"especialidad":"hepatología / infectología","año":"2024"}'),
('child-pugh-cirrosis','Child-Pugh Score','Tabla','Clasificación de severidad en cirrosis','Score Child-Pugh suma 5 variables (1-3 puntos cada una): bilirrubina (menor de 2, 2-3, mayor de 3 mg/dL), albúmina (mayor de 3.5, 2.8-3.5, menor de 2.8 g/dL), INR (menor de 1.7, 1.7-2.3, mayor de 2.3), ascitis (ausente, leve, moderada-severa), encefalopatía (ninguna, grado I-II, grado III-IV). Clase A (5-6): supervivencia 1 año 100%; B (7-9): 80%; C (10-15): 45%. MELD adicional para priorizar trasplante hepático.','{"especialidad":"hepatología"}'),
('forrest-hda','Forrest Classification','Endoscopia','Clasificación de Forrest en hemorragia digestiva alta','Hallazgo endoscópico de úlcera con sangrado: Ia activo en chorro (alto riesgo recidiva, mayor de 80%), Ib sangrado en escurrimiento (alto), IIa vaso visible (alto), IIb coágulo adherente (intermedio), IIc base pigmentada (bajo, 5%), III base limpia (mínimo). Forrest Ia-IIb requieren terapia endoscópica (clip, escleroterapia, electrocoagulación) más IBP IV en infusión 8 mg/h por 72h. Forrest IIc-III: IBP VO ambulatorio, alta temprana.','{"especialidad":"gastroenterología"}'),
('atlanta-pancreatitis','Atlanta Classification Revised 2012','Criterios','Diagnóstico de pancreatitis aguda','Diagnóstico requiere 2 de 3: dolor abdominal típico, lipasa o amilasa mayor de 3 veces el límite superior normal, hallazgos imagenológicos de pancreatitis. Severidad: leve (sin falla orgánica ni complicaciones locales), moderada (falla orgánica transitoria menor de 48h o complicaciones locales), severa (falla orgánica persistente). Manejo inicial: reanimación con cristaloides (no Ringer lactato más Hartmann), analgesia, vía oral tras 24-48h si tolera, antibióticos solo si infección documentada.','{"especialidad":"gastroenterología / urgencias","año":"2012"}'),
('roma-iv-sii','Roma IV Criteria 2016','Síndrome intestino irritable','Criterios diagnósticos de síndrome de intestino irritable','Dolor abdominal recurrente al menos 1 día por semana en los últimos 3 meses asociado a 2 o más de: defecación, cambio en frecuencia, cambio en forma/consistencia de heces. Subtipos: SII-C (constipación), SII-D (diarrea), SII-M (mixto), SII-U (no clasificable). Diagnóstico clínico tras descartar banderas rojas (sangrado, pérdida de peso, anemia, edad mayor de 50 con síntomas nuevos, antecedente familiar de cáncer colorrectal). Tratamiento: dieta baja en FODMAP, fibra soluble, antiespasmódicos.','{"especialidad":"gastroenterología","año":"2016"}'),
('acg-2024-colitis-ulcerosa','ACG Ulcerative Colitis 2024','Tabla 6','Tratamiento por severidad de colitis ulcerosa','Leve a moderada: mesalazina vía oral 2-4.8 g/día + rectal en proctitis/colitis izquierda. Falla o moderada-severa: corticoide vía oral (prednisona 40-60 mg/día) por 2-3 semanas con reducción gradual. Refractaria o dependiente de corticoide: inmunomodulador (azatioprina 2-2.5 mg/kg/día) o biológico (anti-TNF como infliximab, adalimumab; o vedolizumab; o ustekinumab; o tofacitinib). Brote severo: corticoide IV, considerar colectomía si falla a 3-5 días.','{"especialidad":"gastroenterología","año":"2024"}'),
('acg-2018-crohn','ACG Crohn Disease 2018','Tabla 4','Tratamiento de enfermedad de Crohn','Leve: budesonida ileal 9 mg/día (ileítis terminal) o mesalazina (eficacia limitada). Moderada-severa: corticoide para inducción + inmunomodulador (azatioprina, 6-MP, metotrexato) o biológico (anti-TNF como infliximab/adalimumab, ustekinumab, vedolizumab, risankizumab). Tabaco aumenta exacerbaciones; cesación es crítica. Tamizaje de complicaciones: estenosis, fístulas, abscesos con RM enterografía o entero-TC. Mantenimiento de remisión esencial; no corticoide crónico.','{"especialidad":"gastroenterología","año":"2018"}'),
('maastricht-vi-hpylori','Maastricht VI/Florence 2022','Recomendación 5','Erradicación de Helicobacter pylori','Primera línea sin alergia a penicilina ni exposición previa a claritromicina: cuádruple terapia con IBP + amoxicilina + claritromicina + metronidazol por 14 días. Alternativa: cuádruple con bismuto (IBP + bismuto + tetraciclina + metronidazol) por 10-14 días. Confirmar erradicación con prueba de aliento con urea o antígeno fecal 4 semanas tras terminar tratamiento. Si falla: terapia rescate con levofloxacino o cuádruple con bismuto. Recurrencia mayor de 12 meses tras infección original es rara.','{"especialidad":"gastroenterología","año":"2022"}'),

-- ═══ Oncología básica ════════════════════════════════════════════════════
('uspstf-2023-cancer-prostata','USPSTF Prostate Cancer Screening 2018','Recomendación C','Tamizaje de cáncer de próstata con PSA','Hombres de 55-69 años: decisión individualizada sobre PSA tras informar riesgos (sobrediagnóstico, sobretratamiento, complicaciones de biopsia) y beneficios (reducción modesta de mortalidad por cáncer de próstata). Hombres mayor de 70 años: NO se recomienda tamizaje rutinario. Factores que justifican discusión más temprana (40-55 años): afroamericanos, antecedente familiar primer grado de cáncer próstata. PSA aislado tiene baja especificidad; uso de modelos multivariables (PCPT, prostate-MRI) mejora discriminación.','{"especialidad":"urología / oncología","año":"2018"}'),
('uspstf-2021-cancer-pulmon-ldct','USPSTF Lung Cancer 2021','Recomendación B','Tamizaje de cáncer de pulmón con LDCT','Tamizaje anual con TC torácica de baja dosis (LDCT) en adultos 50-80 años con historia de tabaquismo ≥20 paquetes-año y que actualmente fuman o dejaron de fumar en los últimos 15 años. Suspender tamizaje al cumplir 15 años desde cesación o si ya no se beneficiaría por comorbilidad. Sistema Lung-RADS para reporte. Reducción de mortalidad por cáncer pulmón aproximadamente 20%.','{"especialidad":"oncología / neumología","año":"2021"}'),
('who-escala-dolor','WHO Pain Ladder','Escalón','Escalera analgésica de la OMS para dolor oncológico','Escalón 1 (dolor leve, EVA 1-3): paracetamol y/o AINE ± adyuvante. Escalón 2 (dolor moderado, EVA 4-6): opioide débil (tramadol, codeína) + escalón 1 ± adyuvante. Escalón 3 (dolor severo, EVA 7-10): opioide fuerte (morfina, oxicodona, fentanilo, metadona) + escalón 1 ± adyuvante. Vías preferidas: VO, transdérmica. Rescate 10-15% de dosis basal cada 1h si oral inmediato. Manejo de efectos: laxantes desde inicio (estreñimiento es universal), antieméticos, rotación de opioide si toxicidad o pobre respuesta.','{"especialidad":"oncología / cuidados paliativos"}'),
('aahpm-cuidados-paliativos','AAHPM Palliative Care 2018','Recomendación','Indicaciones de cuidados paliativos tempranos','Iniciar cuidados paliativos al diagnóstico de enfermedad seria/avanzada, no solo en fase terminal: cáncer metastásico, IC NYHA III-IV, EPOC GOLD 4, demencia avanzada, ELA, ERC en diálisis con deterioro funcional. Cuidados paliativos tempranos mejoran calidad de vida, reducen depresión, optimizan uso de recursos y pueden prolongar supervivencia en algunos tumores. Incluir manejo de síntomas, planificación anticipada, apoyo psicosocial y espiritual.','{"especialidad":"cuidados paliativos","año":"2018"}'),
('asco-fiebre-neutropenica','IDSA Febrile Neutropenia 2018','Recomendación','Manejo de fiebre neutropénica','Neutropenia febril: neutrófilos menor de 500/μL (o menor de 1000 con descenso esperado) más temperatura ≥38.3°C en una toma o ≥38°C sostenida ≥1h. Riesgo evaluado con MASCC score. Alto riesgo (hospitalización): cefepime 2 g IV c/8h o piperacilina-tazobactam 4.5 g IV c/6h MÁS vancomicina si sospecha de gram positivo o catéter infectado. Bajo riesgo seleccionado: ciprofloxacino + amoxicilina-clavulanato VO ambulatorio. Reevaluar a 48-72h, ampliar cobertura si persiste fiebre.','{"especialidad":"oncología / infectología","año":"2018"}'),

-- ═══ Dermatología ════════════════════════════════════════════════════════
('aad-2023-dermatitis-atopica','AAD Atopic Dermatitis 2023','Recomendación 4','Tratamiento de dermatitis atópica','Emolientes diarios como base de tratamiento en todos los pacientes. Brotes: corticoide tópico de potencia adecuada (baja en cara/pliegues, media-alta en cuerpo) por 7-14 días, después intermitente 2-3 veces/semana en zonas problemáticas. Segunda línea: inhibidores de calcineurina tópicos (tacrolimus, pimecrolimus). Moderada-severa: fototerapia o sistémicos (dupilumab, tralokinumab, inhibidores JAK como upadacitinib/abrocitinib). Educar sobre evitar irritantes, baños tibios, ropa de algodón.','{"especialidad":"dermatología","año":"2023"}'),
('aad-2021-psoriasis','AAD Psoriasis 2020','Sección 4','Tratamiento por severidad en psoriasis','Leve a moderada (BSA menor de 10%, sin afectación ungueal ni articular): tópico — corticoide de alta potencia + análogo de vitamina D (calcipotriol). Moderada a severa o con artritis psoriásica: sistémico — metotrexato 7.5-25 mg semanal, ciclosporina 2.5-5 mg/kg/día, apremilast. Biológicos: anti-TNF (adalimumab, etanercept), anti-IL-17 (secukinumab, ixekizumab), anti-IL-23 (guselkumab, risankizumab). Fototerapia UVB de banda estrecha como alternativa.','{"especialidad":"dermatología","año":"2020"}'),
('aad-acne','AAD Acne 2024','Tabla 3','Tratamiento de acné por severidad','Acné leve: peróxido benzoilo 2.5-10% + retinoide tópico (adapaleno 0.1%, tretinoína 0.025-0.1%) ± antibiótico tópico (clindamicina). Moderado: agregar antibiótico oral (doxiciclina 100 mg/día por 3 meses máximo, después suspender). Severo o nodular cicatricial o refractario: isotretinoína oral 0.5-1 mg/kg/día por 16-20 semanas (dosis acumulada 120-150 mg/kg); requiere anticonceptivo en mujeres edad fértil, monitoreo de transaminasas y lípidos. Mujeres con acné hormonal: anticonceptivo oral combinado o espironolactona.','{"especialidad":"dermatología","año":"2024"}'),
('melanoma-abcde','American Academy of Dermatology','Examen','Criterios ABCDE para sospecha de melanoma','ABCDE clínico: A asimetría (mitad no espeja a la otra), B borde irregular (festoneado, mal definido), C color heterogéneo (varios tonos café, negro, rojo, blanco, azul), D diámetro mayor de 6 mm (no absoluto, melanoma puede ser menor), E evolución (cambio en tamaño, forma, color, síntomas). Lesión sospechosa amerita biopsia escisional con margen 1-3 mm; nunca biopsia parcial salvo lesión muy grande. Auto-examen mensual en pacientes de riesgo, dermatoscopia en consulta.','{"especialidad":"dermatología / oncología"}'),

-- ═══ Oftalmología ════════════════════════════════════════════════════════
('aao-conjuntivitis','AAO Conjunctivitis 2023','Recomendación','Diagnóstico diferencial de conjuntivitis','Viral (más común, 80%, adenovirus): inicio en un ojo, secreción acuosa, hiperemia, sensación de cuerpo extraño, adenopatía preauricular; manejo sintomático (lágrimas artificiales, compresas frías), aislamiento por contagio. Bacteriana: secreción purulenta abundante, sin adenopatía; tratamiento tópico (eritromicina, polimixina-trimetoprim, fluoroquinolona) 5-7 días. Alérgica: bilateral, prurito intenso, hiperemia con quemosis; antihistamínico-estabilizador mastocítico tópico (olopatadina, ketotifeno). Banderas rojas para referir: dolor severo, fotofobia, disminución de agudeza visual, pupila irregular.','{"especialidad":"oftalmología","año":"2023"}'),
('aao-glaucoma','AAO Primary Open-Angle Glaucoma 2020','Recomendación','Tamizaje y manejo inicial de glaucoma de ángulo abierto','Tamizaje en mayores de 40 años con factores de riesgo (afroamericanos, antecedente familiar, miopía alta, DM, uso prolongado de corticoides): tonometría, fondo de ojo (excavación papilar mayor de 0.5 sospechosa), campimetría. Tratamiento de primera línea: análogos de prostaglandinas tópicos (latanoprost, travoprost, bimatoprost) una vez al día por la noche. Objetivo: reducir PIO 25-30% del basal. Segunda línea: betabloqueador tópico (timolol). Trabeculoplastia láser o cirugía si falla farmacológica.','{"especialidad":"oftalmología","año":"2020"}'),
('aao-retinopatia-diabetica','AAO Diabetic Retinopathy 2019','Tabla 2','Tamizaje y estadiaje de retinopatía diabética','DM1: primera evaluación oftalmológica a 5 años del diagnóstico (o desde diagnóstico si pubertad). DM2: al diagnóstico. Embarazo en DM: en primer trimestre con seguimiento trimestral si DM previa. Frecuencia: anual si sin retinopatía, cada 6 meses si NPDR moderada, cada 3-4 meses si NPDR severa o PDR. Estadios: NPDR leve (microaneurismas), moderada, severa (regla 4-2-1: hemorragias en 4 cuadrantes o tortuosidad en 2 o IRMA en 1), PDR (neovasos). Tratamiento: fotocoagulación panretinal en PDR o NPDR severa, anti-VEGF intravítreo en edema macular.','{"especialidad":"oftalmología / endocrinología","año":"2019"}'),

-- ═══ Pediatría adicional ═════════════════════════════════════════════════
('who-ors-diarrea','WHO ORS Treatment 2024','Recomendación','Manejo de diarrea aguda con suero de rehidratación oral','SRO de osmolaridad baja (245 mOsm/L) como primera línea para deshidratación leve-moderada. Plan A (sin deshidratación): SRO tras cada evacuación (lactantes 50-100 mL, niños menor de 2 años 100-200 mL, niños mayores ad libitum) + continuar alimentación. Plan B (deshidratación leve-moderada): SRO 75 mL/kg en 4 horas + reposición de pérdidas. Plan C (severa o shock): rehidratación IV (Ringer lactato o SS) 30 mL/kg primera hora, después 70 mL/kg en 5 horas en menores de 1 año o 2.5 horas en mayores. Zinc 10-20 mg/día por 10-14 días reduce duración y recurrencias.','{"especialidad":"pediatría","año":"2024"}'),
('aap-crup','AAP Croup 2023','Algoritmo','Manejo de laringotraqueítis aguda (crup)','Westley score (estridor, retracciones, entrada de aire, cianosis, nivel de conciencia). Leve (0-2): dexametasona oral 0.6 mg/kg dosis única, alta a domicilio con vigilancia. Moderada (3-7): dexametasona + epinefrina racémica o L-epinefrina nebulizada, observar 4 horas (efecto epinefrina dura 1-2h). Severa (8-11): dexametasona IV/IM + epinefrina nebulizada repetida cada 20-30 min, considerar UCI. Falla: intubación con tubo 0.5-1 mm menor del esperado para edad.','{"especialidad":"pediatría / urgencias","año":"2023"}'),
('gina-2024-asma-pediatrica','GINA 2024 Pediatric','Box 9-7','Tratamiento de asma en niños 6-11 años','Paso 1-2: corticoide inhalado dosis baja diaria + SABA según necesidad. Paso 3: corticoide inhalado dosis media O dosis baja + antileucotrieno. Paso 4: dosis media + LABA o antileucotrieno (LABA solo combinado con CI). Paso 5: dosis alta + LABA + referir a especialista para tiotropio, antileucotrieno o anti-IgE (omalizumab) si fenotipo alérgico. Evaluar control ACT-pediátrico cada 3 meses. Evitar SABA como mantenimiento por aumento de mortalidad/exacerbaciones.','{"especialidad":"pediatría / neumología","año":"2024"}'),
('aap-tdah-2019','AAP ADHD Guideline 2019','Recomendación 4','Manejo del TDAH en niños','Diagnóstico clínico con criterios DSM-5 y evaluación en al menos dos contextos (casa, escuela). Tratamiento por edad: 4-5 años — terapia conductual primero (entrenamiento parental, manejo escolar) por 6 meses; metilfenidato solo si síntomas severos persisten. 6-11 años — terapia conductual + farmacológico (metilfenidato o anfetaminas como primera línea; atomoxetina, guanfacina, clonidina como alternativas). 12-18 años — combinación con asentimiento del adolescente. Vigilar TA, FC, peso, talla, sueño, apetito.','{"especialidad":"pediatría / psiquiatría infantil","año":"2019"}'),
('aap-autismo','AAP Autism Spectrum Disorder 2020','Recomendación 3','Tamizaje y diagnóstico de TEA','Tamizaje universal con M-CHAT-R/F a los 18 y 24 meses en consulta de niño sano. Si positivo: referencia a evaluación especializada (neurodesarrollo, psicología pediátrica) y a programas de intervención temprana sin esperar diagnóstico definitivo. Banderas rojas: sin balbuceo a los 12 meses, sin gesto comunicativo a los 12, sin palabras a los 16, sin frases de 2 palabras a los 24, pérdida de habilidades a cualquier edad. Intervención conductual estructurada antes de los 3 años mejora pronóstico significativamente.','{"especialidad":"pediatría / neurodesarrollo","año":"2020"}'),

-- ═══ Salud mental ════════════════════════════════════════════════════════
('nice-tag-2019','NICE NG113 GAD 2019','Recomendación 1.2','Trastorno de ansiedad generalizada — manejo escalonado','Paso 1: educación y autoayuda guiada (no farmacológica), monitoreo activo 6 semanas. Paso 2: si no mejora, TCC individual o de grupo. Paso 3: si TAG persistente, agregar farmacoterapia con ISRS (sertralina como primera línea, escitalopram alternativo) iniciar dosis baja y titular. Paso 4: si refractario, considerar duloxetina o pregabalina. NO usar benzodiacepinas como tratamiento crónico por riesgo de dependencia y tolerancia. Evaluar respuesta a las 4-6 semanas.','{"especialidad":"psiquiatría","año":"2019"}'),
('nice-toc-2005','NICE NG31 OCD 2005','Sección 5','Trastorno obsesivo-compulsivo — primera línea','TCC con exposición y prevención de respuesta (EPR) como primera línea, especialmente en TOC leve a moderado. Si moderado-severo o refractario a TCC: agregar ISRS (sertralina, fluoxetina, fluvoxamina, paroxetina, citalopram); requieren dosis típicamente más altas que para depresión, respuesta esperada en 8-12 semanas. Si falla a primer ISRS: cambiar a otro ISRS o clomipramina (con monitoreo cardiaco por riesgo de prolongación QT). Refractario: considerar augmentación con antipsicótico atípico a dosis baja.','{"especialidad":"psiquiatría","año":"2005"}'),
('apa-2010-esquizofrenia','APA Schizophrenia 2020','Recomendación','Manejo del primer episodio de esquizofrenia','Iniciar antipsicótico atípico de primera línea (risperidona, olanzapina, aripiprazol, paliperidona) con monitoreo de efectos extrapiramidales, metabólicos (peso, glucosa, lípidos) y prolactina. Dosis efectiva mínima y titular según respuesta. Evaluar adherencia y respuesta a 4-6 semanas; cambiar agente si no hay respuesta significativa. Mantener tratamiento al menos 1-2 años tras remisión. Psicoeducación familiar y servicios de intervención temprana en psicosis mejoran pronóstico funcional.','{"especialidad":"psiquiatría","año":"2020"}'),
('canmat-2016-bipolar','CANMAT Bipolar 2018','Tabla 5','Tratamiento de manía aguda en trastorno bipolar','Primera línea para manía aguda: monoterapia con litio (litemia objetivo 0.8-1.2 mEq/L), valproato, quetiapina, aripiprazol, asenapina, risperidona o cariprazina. Manía severa: combinar estabilizador (litio o valproato) con antipsicótico atípico. Suspender antidepresivos. Mantenimiento tras remisión: litio sigue siendo el más eficaz para profilaxis a largo plazo, con beneficio antisuicida demostrado. Monitorear litemia, función tiroidea, función renal cada 6-12 meses.','{"especialidad":"psiquiatría","año":"2018"}'),
('apa-tept-2017','APA PTSD 2017','Recomendación','Manejo del trastorno por estrés postraumático','Primera línea: psicoterapia trauma-enfocada — terapia cognitivo-conductual centrada en trauma (TCC-CT), terapia de procesamiento cognitivo (CPT), terapia de exposición prolongada (PE), o EMDR. Si no disponible o paciente prefiere: ISRS (sertralina, paroxetina) o venlafaxina ER. Evitar benzodiacepinas (pueden empeorar TEPT, dificultan procesamiento). Insomnio: prazosina para pesadillas relacionadas con trauma. Comorbilidad frecuente: depresión, abuso de sustancias — tratar simultáneamente.','{"especialidad":"psiquiatría","año":"2017"}'),
('uspstf-2021-tabaco','USPSTF Tobacco Cessation 2021','Recomendación A','Intervención para cesación de tabaco','Preguntar sobre tabaquismo en cada consulta. En fumadores: ofrecer asesoría conductual breve (5As: ask, advise, assess, assist, arrange) + farmacoterapia. Primera línea farmacológica: vareniclina (más eficaz, RR de éxito a 6 meses 2.27) o terapia de reemplazo de nicotina combinada (parche + goma/inhalador). Bupropión LP como alternativa. Combinación de farmacoterapia + asesoría conductual aumenta tasa de éxito 70-100% vs cualquiera sola. En embarazo: solo asesoría conductual (TRN solo si beneficio supera riesgo, individualizar).','{"especialidad":"atención primaria / adicciones","año":"2021"}'),

-- ═══ Geriatría adicional ═════════════════════════════════════════════════
('cga-evaluacion-geriatrica','Comprehensive Geriatric Assessment','Marco','Evaluación geriátrica integral','Dominios clínicos: médico (comorbilidades, polifarmacia, dolor), funcional (Barthel para AVD básicas, Lawton para AVD instrumentales, marcha y equilibrio), cognitivo (MMSE/MoCA, ánimo con GDS-15), social (red de apoyo, vivienda, finanzas), nutricional (MNA-SF, pérdida de peso), sensorial (visión, audición). Identifica síndromes geriátricos: caídas, delirium, demencia, depresión, incontinencia, polifarmacia, sarcopenia, fragilidad. Indicada en mayor de 75 años con multimorbilidad, hospitalización reciente o deterioro funcional.','{"especialidad":"geriatría"}'),
('ewgsop-sarcopenia','EWGSOP2 Sarcopenia 2019','Algoritmo','Diagnóstico de sarcopenia','Tamizaje con SARC-F (5 preguntas, ≥4 puntos sugiere sarcopenia). Confirmación: medir fuerza muscular (dinamometría manual: menor de 27 kg en hombres, menor de 16 kg en mujeres). Cuantificar masa muscular (DEXA, BIA, antropometría). Performance física: velocidad de marcha menor de 0.8 m/s, Short Physical Performance Battery menor de 9, Timed Up-and-Go ≥20 s. Tratamiento: ejercicio de resistencia 2-3 veces/semana, proteína 1.2-1.5 g/kg/día, vitamina D si deficiencia.','{"especialidad":"geriatría","año":"2019"}'),
('nice-delirium','NICE CG103 Delirium 2010','Algoritmo','Prevención y manejo de delirium en hospitalización','Tamizaje en cada turno con 4AT (alerta, AMT4 abreviada, atención, agudización). Prevención multifactorial en pacientes en riesgo (mayor de 65, deterioro cognitivo, fractura cadera, enfermedad grave): orientación, reloj y calendario visibles, lentes y audífonos, hidratación y nutrición, movilización temprana, sueño nocturno protegido, manejo de dolor, evitar fármacos de alto riesgo. Tratamiento: identificar y tratar precipitante (infección, deshidratación, medicamentos, dolor); haloperidol 0.5-1 mg VO o IM solo si agitación con riesgo de daño y otras medidas fallidas.','{"especialidad":"geriatría / urgencias","año":"2010"}'),
('stopp-start-2023','STOPP/START Criteria v3 2023','Tabla','Prescripción potencialmente inapropiada en adulto mayor','STOPP: identifica medicamentos a evitar — IBP por más de 8 semanas en dosis terapéutica completa sin indicación clara, AINE sistémicos en hipertensión severa o IC, antimuscarínicos en demencia, sulfonilureas de larga duración en DM. START: identifica omisiones — vacuna influenza anual, vacuna neumocócica, anticoagulación en FA con CHA2DS2-VASc ≥2, IECA en ICC con FEVI reducida, calcio y vitamina D en osteoporosis, antidepresivo en depresión moderada-severa. Revisión sistemática reduce eventos adversos en 35-40%.','{"especialidad":"geriatría / farmacología","año":"2023"}'),

-- ═══ Ginecología/Obstetricia ══════════════════════════════════════════════
('figo-2018-suba','FIGO 2018 AUB','PALM-COEIN','Sangrado uterino anormal — clasificación PALM-COEIN','PALM (estructurales): Pólipo, Adenomiosis, Leiomioma, Malignidad e hiperplasia. COEIN (no estructurales): Coagulopatía, Ovulatoria disfunción, Endometrial, Iatrogénica, No clasificada. Evaluación: historia, exploración, hemoglobina, hCG (descartar embarazo), TSH, ultrasonido transvaginal; biopsia endometrial si mayor de 45 años con sangrado anormal, mayor de 35 con factores de riesgo (obesidad, anovulación), o engrosamiento endometrial mayor de 4 mm posmenopausia. Tratamiento según causa y deseo reproductivo.','{"especialidad":"ginecología","año":"2018"}'),
('eshre-2022-endometriosis','ESHRE Endometriosis 2022','Recomendación','Diagnóstico y tratamiento de endometriosis','Sospecha por dismenorrea progresiva, dispareunia profunda, dolor pélvico crónico, infertilidad. RM pélvica o ecografía transvaginal especializada para endometriosis profunda; laparoscopia diagnóstica reservada si imagen no concluyente y persiste sospecha. Tratamiento médico primera línea: AINE + anticonceptivo combinado oral o progestina (dienogest 2 mg/día). Segunda línea: análogo GnRH con add-back. Cirugía laparoscópica si dolor refractario o endometrioma sintomático. Manejo multidisciplinario (ginecología, dolor, salud mental).','{"especialidad":"ginecología","año":"2022"}'),
('rotterdam-sop','Rotterdam Criteria 2003','Diagnóstico','Síndrome de ovario poliquístico','Diagnóstico requiere 2 de 3: 1) oligo o anovulación (ciclos irregulares, ≥35 días o menor de 21); 2) hiperandrogenismo clínico (hirsutismo, acné, alopecia androgenética) o bioquímico (testosterona total elevada, índice de andrógenos libres alto); 3) ovarios poliquísticos por ultrasonido (≥12 folículos 2-9 mm o volumen ovárico mayor de 10 mL). Descartar otras causas (hiperplasia suprarrenal congénita, Cushing, tumor secretor, hiperprolactinemia). Manejo: pérdida de peso, anticonceptivo combinado, metformina si resistencia a insulina; espironolactona para hirsutismo; clomifeno o letrozol para inducir ovulación.','{"especialidad":"ginecología / endocrinología","año":"2003"}'),
('nams-2022-climaterio','NAMS Hormone Therapy 2022','Posicionamiento','Terapia hormonal en climaterio','Terapia hormonal sigue siendo el tratamiento más eficaz para síntomas vasomotores moderados-severos y atrofia genitourinaria. Beneficio supera riesgo en mujeres menor de 60 años o dentro de 10 años de menopausia, sin contraindicaciones (cáncer mama, ETE/TEP, cardiopatía isquémica, ACV, sangrado vaginal sin diagnosticar). Estrógeno solo si histerectomía; estrógeno + progestina si útero intacto. Atrofia vulvovaginal aislada: estrógeno vaginal en dosis baja. Reevaluar anualmente; mantener mientras beneficio supere riesgo individual.','{"especialidad":"ginecología","año":"2022"}'),
('who-mec-anticonceptivos','WHO Medical Eligibility 2015','Tabla','Criterios de elegibilidad médica para anticoncepción','Categoría 1: usar sin restricción. Categoría 2: ventajas superan riesgos teóricos. Categoría 3: riesgos teóricos superan ventajas (usar solo si alternativas no disponibles). Categoría 4: riesgo de salud inaceptable (no usar). Ejemplos: ACO combinado contraindicado (C4) en mayor de 35 con tabaquismo ≥15 cig/día, HAS severa, ASCVD, TEP/ETE, migraña con aura, lactancia menor de 6 semanas posparto. Métodos de larga acción reversibles (DIU, implante) son C1 en casi todas las condiciones.','{"especialidad":"ginecología / atención primaria","año":"2015"}'),
('hemorragia-posparto-figo','FIGO PPH 2022','Manejo','Hemorragia posparto — manejo escalonado','Hemorragia posparto: pérdida ≥500 mL post-parto vaginal o ≥1000 mL post-cesárea, o cualquier sangrado con compromiso hemodinámico. Manejo simultáneo en cuatro frentes (4Ts: Tono, Trauma, Tejido, Trombina). Primera línea: masaje uterino bimanual + oxitocina 10 UI IV bolo + 40 UI en 1000 mL Ringer a 250 mL/h. Segunda línea: ergometrina 0.2 mg IM (contraindicada en HAS), misoprostol 800-1000 mcg sublingual o rectal, ácido tranexámico 1 g IV. Compresión bimanual, balón intrauterino. Refractario: cirugía (suturas B-Lynch, ligadura de uterinas, histerectomía).','{"especialidad":"obstetricia / urgencias","año":"2022"}'),

-- ═══ Infectología extensa ════════════════════════════════════════════════
('nih-covid-tratamiento-2024','NIH COVID-19 Treatment Guidelines 2024','Recomendación','Tratamiento ambulatorio de COVID-19 con riesgo de progresión','Pacientes con COVID-19 leve a moderado y riesgo alto de progresión (mayor de 65, inmunocomprometidos, comorbilidades): nirmatrelvir/ritonavir (Paxlovid) 300/100 mg c/12h por 5 días dentro de los primeros 5 días desde inicio de síntomas. Verificar interacciones medicamentosas extensas. Alternativa: remdesivir IV 3 días en ambulatorio si Paxlovid contraindicado. NO se recomiendan azitromicina, hidroxicloroquina, ivermectina, vitamina D ni zinc para tratamiento. Corticoide reservado para hospitalizados con requerimiento de oxígeno.','{"especialidad":"infectología","año":"2024"}'),
('cdc-influenza-2024','CDC Influenza 2024','Recomendación','Tratamiento antiviral de influenza','Iniciar antiviral lo antes posible (idealmente dentro de las primeras 48h) en: hospitalizados, enfermedad severa o progresiva, pacientes de alto riesgo (mayor de 65, menor de 5 especialmente menor de 2, embarazo y posparto 2 semanas, comorbilidades crónicas, inmunocompromiso, obesidad mórbida). Oseltamivir 75 mg VO c/12h por 5 días (dosis pediátrica por peso). Alternativas: zanamivir inhalado, peramivir IV, baloxavir VO dosis única. Vacunación anual es la mejor prevención.','{"especialidad":"infectología","año":"2024"}'),
('paho-dengue-2024','PAHO Dengue 2024','Algoritmo','Manejo de dengue por grupos','Grupo A (dengue sin signos de alarma, tolera vía oral, sin riesgo): manejo ambulatorio con hidratación oral y paracetamol; vigilar signos de alarma; control diario hasta 24-48h tras defervescencia. Grupo B (con signos de alarma o riesgo): hospitalizar, hidratación IV con cristaloides isotónicos 5-7 mL/kg/h en 1-2h, reducir según evolución. Grupo C (severo, choque o sangrado severo): UCI, cristaloides 20 mL/kg en bolo 15-30 min, reevaluar, transfundir si choque persistente con anemización. Evitar AINE, aspirina y corticoides. NO antibióticos rutinarios.','{"especialidad":"infectología / urgencias","año":"2024"}'),
('cdc-sifilis-2024','CDC STI Treatment 2024','Sífilis','Tratamiento de sífilis por estadio','Sífilis primaria, secundaria o latente temprana (menor de 1 año): penicilina G benzatínica 2.4 millones UI IM dosis única. Sífilis latente tardía (mayor de 1 año o desconocida): penicilina G benzatínica 2.4 millones UI IM semanal por 3 dosis. Neurosífilis: penicilina G acuosa 3-4 millones UI IV c/4h por 10-14 días. Alergia a penicilina (no embarazo): doxiciclina 100 mg VO c/12h por 14 días (28 días en latente tardía). Embarazo con alergia: desensibilización y penicilina. Seguimiento serológico VDRL/RPR a 6 y 12 meses.','{"especialidad":"infectología","año":"2024"}'),
('dhhs-vih-inicio-tar','DHHS Adult ARV 2024','Recomendación','Inicio de tratamiento antirretroviral','TAR recomendado para todos los pacientes con VIH independientemente de CD4 (incluso ofrecer mismo día). Regímenes preferidos primera línea: bictegravir/tenofovir alafenamida/emtricitabina (Biktarvy) una vez al día (única tableta), o dolutegravir + tenofovir + emtricitabina, o dolutegravir/lamivudina (Dovato). Objetivos: carga viral indetectable a 6 meses, CD4 ascendente, adherencia mayor de 95%. U=U (indetectable = intransmisible): paciente con carga viral suprimida sostenida no transmite sexualmente.','{"especialidad":"infectología","año":"2024"}'),
('who-malaria-2023','WHO Malaria Guidelines 2023','Recomendación','Tratamiento de malaria por Plasmodium','Malaria no complicada por P. falciparum: combinación basada en artemisinina (artemether-lumefantrina, artesunato-amodiaquina) por 3 días. P. vivax o P. ovale: cloroquina + primaquina (14 días para erradicación de hipnozoítos hepáticos), verificar G6PD antes de primaquina. Malaria severa: artesunato IV 2.4 mg/kg a las 0, 12, 24h y después cada 24h hasta tolerar vía oral, completar 3 días con combinación oral. Profilaxis viajero: atovaquona-proguanil, doxiciclina o mefloquina según zona.','{"especialidad":"infectología","año":"2023"}'),
('cdc-itu-tratamiento','IDSA UTI 2022','Recomendación','Tratamiento de cistitis aguda no complicada','Mujer no embarazada con cistitis no complicada: nitrofurantoína 100 mg VO c/12h por 5 días o fosfomicina 3 g VO dosis única o trimetoprim-sulfametoxazol 160/800 mg c/12h por 3 días (si resistencia local menor de 20%). Evitar fluoroquinolonas como primera línea por resistencia y efectos adversos. Pielonefritis no complicada: fluoroquinolona oral 7 días o cefalosporina de 3ª generación IV/IM seguido de oral según cultivo. Embarazadas: cefalexina o nitrofurantoína (evitar en 3er trimestre cercano al parto y G6PD).','{"especialidad":"infectología / urología","año":"2022"}'),

-- ═══ Otros ════════════════════════════════════════════════════════════════
('acp-2017-lumbalgia','ACP Low Back Pain 2017','Recomendación','Manejo de lumbalgia aguda y subaguda','Primera línea no farmacológica: calor superficial, masaje, acupuntura, manipulación espinal. Si farmacológico necesario: AINE como primera línea (ibuprofeno, naproxeno) en menor dosis efectiva por tiempo corto, o relajante muscular (ciclobenzaprina). NO se recomienda paracetamol, opioides ni corticoides sistémicos en lumbalgia aguda no específica. Imagen (radiografía, RM) NO indicada en primer mes sin banderas rojas (déficit neurológico progresivo, síndrome cauda equina, fiebre, antecedente oncológico, trauma significativo, edad mayor de 70 con osteoporosis). Educación: actividad ligera vs reposo.','{"especialidad":"reumatología / dolor","año":"2017"}'),
('acr-af-artrosis','ACR/Arthritis Foundation OA 2019','Recomendación','Manejo de osteoartritis de rodilla y cadera','Primera línea no farmacológica: ejercicio (aeróbico de bajo impacto y fortalecimiento), pérdida de peso si IMC mayor de 25, terapia física, autoeducación. Farmacológico: AINE tópicos primera línea en rodilla (diclofenaco gel). AINE oral si tópico insuficiente, a dosis efectiva mínima y por tiempo corto. Inyección intraarticular de corticoide para exacerbación dolorosa de rodilla o cadera. Paracetamol uso limitado por modesta eficacia. NO se recomiendan glucosamina, condroitina, hialuronato intraarticular. Considerar artroplastia si dolor refractario y deterioro funcional.','{"especialidad":"reumatología / ortopedia","año":"2019"}'),
('aua-iut-recurrente','AUA Recurrent UTI 2022','Recomendación','Prevención de infecciones urinarias recurrentes en mujeres','Mujer con ≥2 ITUs en 6 meses o ≥3 en 12 meses: profilaxis continua con nitrofurantoína 50-100 mg/noche por 6-12 meses, o trimetoprim-sulfametoxazol 40/200 mg/noche; alternativa postcoital. Profilaxis no antibiótica: arándano (modesta evidencia), estrógeno vaginal en posmenopáusicas (eficaz), D-manosa 2 g/día. Cultivo en cada episodio para confirmar y guiar tratamiento. Evaluación urológica con cistoscopia si ITU recurrente complicada o hematuria persistente.','{"especialidad":"urología / infectología","año":"2022"}'),
('cdc-opioides-2022','CDC Opioid Prescribing 2022','Recomendación','Prescripción de opioides para dolor crónico no oncológico','Optimizar terapia no opioide primero (AINE, paracetamol, antidepresivos para dolor neuropático, ejercicio, TCC). Si se considera opioide: iniciar liberación inmediata a dosis efectiva mínima por tiempo corto (3 días suelen bastar para dolor agudo). Dolor crónico: discutir riesgos y beneficios, establecer objetivos funcionales, evaluar riesgo de uso problemático (PDMP, screening). Evitar combinación con benzodiacepinas. Si dosis mayor de 50 MME/día reevaluar beneficio; mayor de 90 MME/día requiere justificación cuidadosa y considerar especialista en dolor.','{"especialidad":"dolor / atención primaria","año":"2022"}'),
('kdigo-2012-aki','KDIGO AKI 2012','Tabla 2','Diagnóstico y estadiaje de lesión renal aguda','Diagnóstico de LRA: aumento de creatinina ≥0.3 mg/dL en 48h o ≥1.5 veces el basal en 7 días, o diuresis menor de 0.5 mL/kg/h por 6h. Etapa 1: cr 1.5-1.9x basal o aumento ≥0.3, diuresis menor de 0.5 mL/kg/h 6-12h. Etapa 2: cr 2-2.9x, diuresis menor de 0.5 mL/kg/h ≥12h. Etapa 3: cr ≥3x o ≥4.0 mg/dL o necesidad de diálisis, diuresis menor de 0.3 mL/kg/h ≥24h o anuria ≥12h. Manejo: identificar y tratar causa (prerrenal, intrarrenal, posrenal), optimizar volumen, evitar nefrotóxicos, ajustar fármacos por TFG.','{"especialidad":"nefrología","año":"2012"}'),
('acog-hta-gestacional','ACOG Hypertension in Pregnancy 2020','Recomendación','Clasificación y manejo de HAS en embarazo','HAS gestacional: TA ≥140/90 después de semana 20 sin proteinuria ni datos de preeclampsia, resuelve posparto. Preeclampsia: HAS + proteinuria o disfunción de órgano (trombocitopenia, transaminasas elevadas, dolor abdominal, síntomas visuales/cefalea, edema pulmonar, creatinina elevada). Antihipertensivos en embarazo: labetalol (primera línea), nifedipino, alfa-metildopa. Evitar IECA, ARA II, atenolol. Sulfato de magnesio para profilaxis de eclampsia en preeclampsia severa. Aspirina baja dosis 81-150 mg/día desde semana 12 en mujeres con factores de riesgo de preeclampsia.','{"especialidad":"obstetricia","año":"2020"}'),
('paho-zika-embarazo','PAHO Zika in Pregnancy 2017','Recomendación','Manejo de sospecha de Zika en embarazada','Toda embarazada con exposición o residencia en zona endémica debe tamizarse por síntomas en cada consulta prenatal. Sintomática (exantema, fiebre, conjuntivitis no purulenta, artralgias) o expuesta confirmada: RT-PCR sérica y urinaria en primeras 2 semanas; serología IgM tras 2 semanas. Si positivo: ultrasonido obstétrico mensual buscando microcefalia, calcificaciones cerebrales, alteraciones del flujo. Educar sobre repelente (DEET 30%) seguro en embarazo, ropa protectora, evitar viaje a zonas endémicas. Comunicación de pareja: usar condón hasta nacimiento si pareja varón expuesto.','{"especialidad":"infectología / obstetricia","año":"2017"}'),
('aha-tev-tratamiento','ASH VTE 2020','Recomendación','Anticoagulación inicial en tromboembolia venosa','Diagnóstico confirmado de TEV (TVP o TEP) sin contraindicación: iniciar anticoagulación inmediata con anticoagulante oral directo (apixabán 10 mg c/12h por 7 días después 5 mg c/12h, o rivaroxabán 15 mg c/12h por 21 días después 20 mg/día) sin necesidad de heparina inicial, o dabigatrán/edoxabán tras 5-10 días de HBPM. Duración: 3 meses si provocado y resuelto factor; mayor de 3 meses o indefinido si no provocado o factor persistente. En cáncer activo: HBPM o ACOD por al menos 6 meses.','{"especialidad":"hematología / urgencias","año":"2020"}'),
('cdc-hepatitis-b-tamizaje','CDC Hepatitis B Screening 2023','Recomendación','Tamizaje de hepatitis B en adultos','Tamizaje universal al menos una vez en la vida en todos los adultos ≥18 años con triple panel: HBsAg, anti-HBs, anti-HBc total. Resultados: HBsAg+ infección crónica (referir hepatología, evaluar carga viral, ALT, cirrosis); anti-HBs+ y anti-HBc+ infección resuelta (sin tratamiento, riesgo de reactivación con inmunosupresión); anti-HBs+ aislado inmunidad por vacuna; negativos todos: vacunar. Vacuna hepatitis B universal en adultos 19-59 años, ≥60 con factores de riesgo.','{"especialidad":"infectología / hepatología","año":"2023"}'),
('uspstf-tamizaje-vih','USPSTF HIV Screening 2019','Recomendación A','Tamizaje universal de VIH','Tamizaje rutinario en adolescentes y adultos 15-65 años. Mujeres embarazadas: tamizaje en cada embarazo (primer trimestre y rescreen tercer trimestre si factores de riesgo). Frecuencia: al menos una vez en la vida; anual si comportamientos de alto riesgo (parejas múltiples, HSH, inyección de drogas, parejas con VIH, ITS recurrentes). Prueba: ELISA de cuarta generación detecta IgG/IgM y antígeno p24 (ventana 2-3 semanas). Confirmación con Western blot o diferenciación de anticuerpos. Diagnóstico positivo: vincular a atención y TAR inmediato.','{"especialidad":"infectología / atención primaria","año":"2019"}'),
('aap-vacunas-mexico-2024','Cartilla Nacional MX 2024','Esquema','Esquema de vacunación pediátrica en México','Nacimiento: BCG (intradérmica deltoides derecho), HB primera dosis. 2 meses: HB segunda, hexavalente (DTaP+Hib+VPI+HB) primera, neumococo conjugada primera, rotavirus primera. 4 meses: hexavalente segunda, neumococo segunda, rotavirus segunda. 6 meses: hexavalente tercera, influenza anual (en temporada). 7 meses: influenza segunda dosis si primera vacuna. 1 año: SRP primera, neumococo refuerzo, hepatitis A primera. 18 meses: DTaP refuerzo, hepatitis A segunda. 4 años: DTaP segundo refuerzo, SRP refuerzo, VPI refuerzo. 11 años: VPH 2 dosis (0, 6 meses), Tdpa refuerzo.','{"especialidad":"pediatría / prevención","año":"2024"}')

on conflict (id) do update set
  source = excluded.source,
  page = excluded.page,
  title = excluded.title,
  content = excluded.content,
  meta = excluded.meta;
